# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9784ec0d26a68cb3e8659a4fdbc943349e38d7d56196bca587f85bc427d66b6d8f8bddebd954c42b3919b969c129c64d60c2e2bfacce554d946da5ca2ed3950

test:
  secret_key_base: 11b827965d870af0f77b3ad617453f50eaabaad5bb689a13f73e286a529f60c7d14dc92f41144137134c834418b1910085e630c8c58af2e7c330b90232c3d7e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
